name: Selenium Tests

on:
  push:
    branches:
      - main   # 在推送到 main 分支时触发
  pull_request:
    branches:
      - main   # 在创建 pull request 时触发

jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # 选择 GitHub Actions 提供的环境

    services:
      - name: selenium/standalone-chrome
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g   # 增加共享内存大小

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'

      - name: Install dependencies
        run: mvn install  # 安装 Maven 依赖

      - name: Run Selenium Tests
        run: mvn test   # 运行 Selenium 测试
